# Generated by Django 5.1.6 on 2025-02-24 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_title', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('username', models.CharField(max_length=100, null=True)),
                ('create_post', models.DateTimeField(auto_now_add=True)),
                ('update_post', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'blog_project',
            },
        ),
    ]
